import { Tool, Prompt, Category } from './types.ts';

export const initialCategories: Category[] = [
  { id: 'cat_1', name: 'كتابة' },
  { id: 'cat_2', name: 'تسويق' },
  { id: 'cat_3', name: 'برمجة' },
  { id: 'cat_4', name: 'تصميم' },
  { id: 'cat_5', name: 'أعمال' },
  { id: 'cat_6', name: 'تعليم' },
  { id: 'cat_7', name: 'صوت' },
  { id: 'cat_8', name: 'إنتاجية' },
];

export const initialTools: Tool[] = [
  {
    id: 'tool_1',
    name: 'Gemini',
    url: 'https://gemini.google.com/',
    description: 'مساعد ذكاء اصطناعي من جوجل قادر على فهم وإنشاء نصوص وصور وأصوات وفيديوهات.',
    categoryIds: ['cat_1', 'cat_5', 'cat_6'],
    personal_rating: 5,
    tags: ['متعدد الوسائط', 'جوجل', 'محادثة'],
  },
  {
    id: 'tool_2',
    name: 'Midjourney',
    url: 'https://www.midjourney.com/',
    description: 'أداة قوية لتوليد الصور بالذكاء الاصطناعي عبر أوامر نصية.',
    categoryIds: ['cat_4'],
    personal_rating: 4,
    tags: ['صور', 'فن', 'ديسكورد'],
  },
  {
    id: 'tool_3',
    name: 'GitHub Copilot',
    url: 'https://copilot.github.com/',
    description: 'مساعد برمجي بالذكاء الاصطناعي يساعد في كتابة الأكواد البرمجية بشكل أسرع وأكثر كفاءة.',
    categoryIds: ['cat_3'],
    personal_rating: 5,
    tags: ['VS Code', 'برمجة', 'GitHub'],
  },
  {
    id: 'tool_4',
    name: 'Leonardo.Ai',
    url: 'https://leonardo.ai/',
    description: 'منصة متكاملة لإنشاء أصول مرئية عالية الجودة للألعاب والتصاميم باستخدام الذكاء الاصطناعي.',
    categoryIds: ['cat_4'],
    personal_rating: 4,
    tags: ['ألعاب', 'صور', 'نماذج مخصصة'],
  },
  {
    id: 'tool_5',
    name: 'Notion AI',
    url: 'https://www.notion.so/product/ai',
    description: 'مساعد ذكاء اصطناعي مدمج في Notion يساعد على الكتابة والتلخيص وتنظيم الأفكار.',
    categoryIds: ['cat_1', 'cat_8'],
    personal_rating: 4,
    tags: ['Notion', 'تنظيم', 'كتابة'],
  },
  {
    id: 'tool_6',
    name: 'ElevenLabs',
    url: 'https://elevenlabs.io/',
    description: 'أداة رائدة في تحويل النص إلى كلام وتوليد أصوات بشرية واقعية للغاية.',
    categoryIds: ['cat_7'],
    personal_rating: 5,
    tags: ['صوت', 'تعليق صوتي', 'TTS'],
  },
];

export const initialPrompts: Prompt[] = [
  {
    id: 'prompt_1',
    toolId: 'tool_1',
    title: 'كتابة منشور لينكدإن',
    promptText: 'اكتب لي منشورًا احترافيًا على لينكدإن حول أهمية استخدام الذكاء الاصطناعي في التسويق الرقمي. يجب أن يكون المنشور جذابًا وموجزًا ويتضمن 3 هاشتاقات ذات صلة.',
    description: 'برومبت لإنشاء محتوى لمنصة لينكدإن يركز على التسويق.',
    categoryId: 'cat_2',
    personal_rating: 4,
  },
  {
    id: 'prompt_2',
    toolId: 'tool_1',
    title: 'تلخيص مقال طويل',
    promptText: 'لخص لي المقال التالي في 5 نقاط رئيسية:\n[الصق المقال هنا]',
    description: 'برومبت سريع لتلخيص النصوص والمقالات الطويلة.',
    categoryId: 'cat_1',
    personal_rating: 5,
  },
   {
    id: 'prompt_3',
    toolId: 'tool_2',
    title: 'تصميم شعار لشركة تقنية',
    promptText: 'logo for a tech startup called "FutureAI", minimalist, vector, blue and green colors, futuristic font --ar 1:1',
    description: 'برومبت لتصميم شعار بسيط وعصري باستخدام Midjourney.',
    categoryId: 'cat_4',
    personal_rating: 4,
  },
  {
    id: 'prompt_4',
    toolId: 'tool_3',
    title: 'شرح كود برمجي',
    promptText: 'Explain this python function, what it does, its inputs, and its outputs.\n\n```python\ndef calculate_fibonacci(n):\n    if n <= 0:\n        return []\n    elif n == 1:\n        return [0]\n    a, b = 0, 1\n    result = [a, b]\n    while len(result) < n:\n        a, b = b, a + b\n        result.append(b)\n    return result\n```',
    description: 'برومبت لمساعد GitHub Copilot لشرح وظيفة برمجية معقدة.',
    categoryId: 'cat_3',
    personal_rating: 5,
  },
  {
    id: 'prompt_5',
    toolId: 'tool_2',
    title: 'مشهد سينمائي مستقبلي',
    promptText: 'cinematic shot, a neon-lit futuristic city street at night, rain-slicked pavement reflecting the glowing signs, a lone figure in a trench coat walks away from the camera, Blade Runner style, hyperrealistic, 8k --ar 16:9',
    description: 'برومبت لإنشاء صورة سينمائية بأسلوب فيلم Blade Runner.',
    categoryId: 'cat_4',
    personal_rating: 5,
  },
  {
    id: 'prompt_6',
    toolId: 'tool_1',
    title: 'كتابة نص إعلان تسويقي',
    promptText: 'اكتب لي نص إعلان قصير وجذاب لمنتج "سماعات أذن لاسلكية" يستهدف الشباب. ركز على ميزات عزل الضوضاء وعمر البطارية الطويل. استخدم نبرة حماسية.',
    description: 'برومبت لإنشاء نسخة إعلانية (copy) لمنتج معين.',
    categoryId: 'cat_2',
    personal_rating: 4,
  },
  {
    id: 'prompt_7',
    toolId: 'tool_4',
    title: 'تصميم شخصية لعبة',
    promptText: 'game character concept art, a fierce elven warrior princess, intricate silver armor with glowing green accents, holding a crystal spear, magical forest background, detailed, fantasy, RPG character',
    description: 'برومبت لتصميم شخصية لعبة خيالية باستخدام Leonardo.Ai.',
    categoryId: 'cat_4',
    personal_rating: 4,
  },
];
